### PR TITLE
Fix ALTER PROTO BUNDLE to accept combination of INSERT/UPDATE/DELETE

### LINKED ISSUE #200: Bug: ALTER PROTO BUNDLE is not correctly implemented
Currently, `AlterProtoBundle` only permit the one of `INSERT`, `UPDATE`, or `DELETE`, but formal syntax can accept all of them.
```
ALTER PROTO BUNDLE
[ INSERT ( <proto_type_name> , .... ) ]
[ UPDATE ( <proto_type_name> , .... ) ]
[ DELETE ( <proto_type_name> , .... ) ]
```

Also, `ALTER PROTO BUNDLE;` is a valid statement.

### PR DESCRIPTION
**Pull request by apstndb**
This PR fixes `ALTER PROTO BUNDLE` statemant to accept combination of  `INSERT`, `UPDATE`, and `DELETE`.

Breaking changes:

- It changes structure of `ast.AlterProtoBundle` struct.

Fixes #200

### CODE REVIEW

File: ast/ast.go [hunk 1]
```diff
@@ -1867,14 +1858,17 @@ type CreateProtoBundle struct {
 
 // AlterProtoBundle is ALTER PROTO BUNDLE statement node.
 //
-//	ALTER PROTO BUNDLE {{.Alteration | sql}}
+//	ALTER PROTO BUNDLE {{.Insert | sqlOpt}} {{.Update | sqlOpt}} {{.Delete | sqlOpt}}
```
Comment (makenowjust) [inline ast/ast.go:1861]: Are they actually restricted to this order? Also, is it not possible to specify the same operation multiple times?

Comment (apstndb) [reply ast/ast.go:1861]: Don't permit reverse order.
```
spanner> ALTER PROTO BUNDLE DELETE(ProtoType) UPDATE(ProtoType);
ERROR: error on create op: rpc error: code = InvalidArgument desc = Error parsing Spanner DDL statement: ALTER PROTO BUNDLE DELETE(ProtoType) UPDATE(ProtoType) : Syntax error on line 1, column 38: Expecting 'EOF' but found 'UPDATE'
```
and don't permit duplicated.

```
spanner> ALTER PROTO BUNDLE UPDATE(ProtoType) UPDATE(ProtoType);
ERROR: error on create op: rpc error: code = InvalidArgument desc = Error parsing Spanner DDL statement: ALTER PROTO BUNDLE UPDATE(ProtoType) UPDATE(ProtoType) : Syntax error on line 1, column 38: Expecting 'EOF' but found 'UPDATE'
```
